### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rastacalavera**
I don't know how to do the docker run commands for this

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-chevereto/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

I changed the compose file to include the LSIO mariadb image
## Benefits of this PR and context:

As it is written currently, the compose file presents the user with an unusable image. At the install screen, it asks the user to sign in to a database which does not exist.
## How Has This Been Tested?

My included compose file has been tested and works as expected. This was all done on a raspberry pi 4 and does not impact anything other than the readme for the package.

### CODE REVIEW

**Review by Roxedus — CHANGES_REQUESTED** [review]
You have clearly not read the [contributing guidelines](https://github.com/linuxserver/docker-chevereto/blob/master/.github/CONTRIBUTING.md?rgh-link-date=2021-04-28T00%3A07%3A40Z) as you stated above. These changes will not stick.

**Comment by rastacalavera** [comment]
Hey man I was trying. If you go back and look at the discord history I was
actively asking questions and trying to learn. It was as simple as editing
a plain mark down file. The project had that template and work flow I had
to try to figure out. There were a lot of new things to learn and try to
understand. I don’t know if you were trying to make me feel bad with that
comment or not but either way it wasn’t helpful. I did try to read the docs
and ask for help. I am not trying to waste your time I am trying to help
the project and learn.

**Comment by Roxedus** [comment]
We spoke on discord about changing the readme-vars.yml file. I forget how the whole timeline landed, but I was not trying to be rude. Did you base this PR from the wrong branch? as I see you still have the branch where you edited the correct file.

**Comment by rastacalavera** [comment]
I may have it’s been awhile. I am dealing with some personal stuff so I
haven’t been as active as I was. I’ll revisit this in a week hopefully.

**Comment by TheSpad** [comment]
Obsoleted by https://github.com/linuxserver/docker-chevereto/pull/9

**Pull request closed without merging**
